import { useState } from 'react'
import type { FormEvent } from 'react'
import { authApi } from './lib/authApi'
import type { PortalAccount } from './lib/portal'
import { FirstLoginSetup, MemberApprovals } from './Portal'

export default function MainAccess({ back, startJourney, continueJourney, account, loading, accountChanged }: { back: () => void; startJourney: () => void; continueJourney?: () => void; account: PortalAccount | null; loading: boolean; accountChanged: (account: PortalAccount | null) => void }) {
  const logout = async () => { await authApi.logout().catch(() => undefined); accountChanged(null) }
  if (loading) return <section className="security-setup"><p>Checking secure access…</p></section>
  if (!account) return <MainLogin login={accountChanged} back={back} />
  if (account.mustChangePassword) return <FirstLoginSetup account={account} finish={async (password, pin) => { await authApi.finishFirstLogin(password, pin); accountChanged({ ...account, mustChangePassword: false }) }} logout={logout} />
  return <section className="portal-shell"><header className="portal-head"><button className="portal-wordmark" onClick={back}><span>ZERO 2 HERO</span><b>MEMBER ACCESS</b></button><nav>{account.role === 'founder' && <span className="founder-access-label">Founder dashboard</span>}</nav><div className="portal-profile"><span>{account.displayName.slice(0, 2).toUpperCase()}</span><div><b>{account.displayName}</b><small>{account.role}</small></div><button onClick={logout}>Log out</button></div></header><main className="portal-main">{account.role === 'founder' ? <MemberApprovals currentAccount={account} /> : <section className="member-home"><small>WELCOME BACK, HERO</small><h1>Your next Mission<br />starts here.</h1><p>Open your Journey dashboard or begin a new path toward a real skill you can prove.</p><div className="hero-actions">{continueJourney && <button className="primary" onClick={continueJourney}>Continue my Journey</button>}<button className="secondary" onClick={startJourney}>Start a new Journey</button></div></section>}</main></section>
}

function MainLogin({ login, back }: { login: (account: PortalAccount) => void; back: () => void }) {
  const [mode, setMode] = useState<'login' | 'signup' | 'reset'>('login')
  const [username, setUsername] = useState(''), [displayName, setDisplayName] = useState(''), [password, setPassword] = useState(''), [pin, setPin] = useState(''), [message, setMessage] = useState('')
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setMessage('')
    try {
      if (mode === 'login') { const result = await authApi.login(username, password, 'zero2hero'); login(result.account); return }
      if (mode === 'reset') { const result = await authApi.requestReset(username, pin, 'zero2hero'); setMode('login'); setPin(''); setMessage(result.message); return }
      await authApi.signup(displayName.trim() || username.trim(), username, 'zero2hero'); setMode('login'); setPassword(''); setMessage('Signup sent. A Founder must approve it before you can log in.')
    } catch (error) { setMessage(error instanceof Error ? error.message : 'The request failed.') }
  }
  return <section className="portal-login"><button className="back-link" onClick={back}>← Back to home</button><div className="portal-login-grid"><div className="portal-login-story"><span className="portal-chip">ZERO 2 HERO MEMBER ACCESS</span><h1>Build the skill.<br /><em>Show the work.</em></h1><p>Regular ZERO 2 HERO accounts open the Journey experience. Your Shot course access is requested separately through the public Your Shot portal link.</p><div className="positive-card"><b>SECURE ACCESS</b><p>Passwords are hashed on the server. Sessions use secure, HttpOnly cookies and account approval stays with the Founder.</p></div></div><form className="portal-login-card" onSubmit={submit}><small>ZERO 2 HERO</small><h2>{mode === 'login' ? 'Log in.' : mode === 'signup' ? 'Request an account.' : 'Request a password reset.'}</h2>{mode === 'signup' && <label><span>Display name</span><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label>}<label><span>Username</span><input required value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label>{mode === 'login' && <label><span>Password</span><input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></label>}{mode === 'reset' && <label><span>Security PIN</span><input required inputMode="numeric" pattern="[0-9]{4,8}" type="password" value={pin} onChange={(event) => setPin(event.target.value)} placeholder="4–8 digits" /></label>}{mode === 'signup' && <p className="default-password-note">After approval, your temporary password will be <b>{username || 'username'}0205</b>. You must replace it with a strong password and create a security PIN at first login.</p>}{message && <p className="form-message">{message}</p>}<button className="primary full" type="submit">{mode === 'login' ? 'Log in' : mode === 'signup' ? 'Send signup request' : 'Send reset request'}</button><button className="text-button" type="button" onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setMessage('') }}>{mode === 'login' ? 'Create a ZERO 2 HERO account' : 'Back to login'}</button>{mode === 'login' && <button className="text-button" type="button" onClick={() => { setMode('reset'); setMessage('') }}>Forgot password? Request a reset</button>}</form></div></section>
}
